name: Trigger deploy on push to master

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Install builds plugin
        run: heroku plugins:install heroku-builds

      - name: test
        run: ls -alh

      - name: Build app into tarball
        run: |
          git fetch --prune --unshallow --tags
          python setup.py sdist --formats=gztar

      - name: Create Heroku Build
        run: heroku builds:create -a jacob-nesbitt-playground --source-tar=dist/$(python setup.py --fullname).tar.gz
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY  }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL  }}

      # - uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: "jacob-nesbitt-playground"
      #     heroku_email: ${{secrets.HEROKU_EMAIL}}
